/**
 * PDF Generation Service (PDFKit)
 */
const PDFDocument = require("pdfkit");
function generateWorkOrderPdf(workOrder, recommendation, score, detection, report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
    doc.fontSize(20).font("Helvetica-Bold").text("SENTRIROAD - WORK ORDER", { align: "center" });
    doc.moveDown(0.3).fontSize(10).font("Helvetica").text(`Work Order ID: ${workOrder.id}`, { align: "center" });
    doc.text(`Generated: ${new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST`, { align: "center" }).moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke().moveDown(1);
    doc.fontSize(13).font("Helvetica-Bold").text("LOCATION").moveDown(0.2);
    doc.fontSize(10).font("Helvetica").text(`Address: ${workOrder.location.address}`).text(`GPS: ${workOrder.location.gps.lat}, ${workOrder.location.gps.lng}`).text(`Report ID: ${report.id}`).moveDown(0.8);
    doc.fontSize(13).font("Helvetica-Bold").text("AI DETECTION").moveDown(0.2);
    doc.fontSize(10).font("Helvetica").text(`Damage Type: ${detection.damage_type.toUpperCase()}`).text(`Confidence: ${(detection.confidence * 100).toFixed(1)}%`).moveDown(0.8);
    doc.fontSize(13).font("Helvetica-Bold").text("PRIORITY SCORE").moveDown(0.2);
    doc.fontSize(10).font("Helvetica").text(`Urgency Score: ${workOrder.urgency_score}/100`);
    const fb = score.factor_breakdown;
    Object.entries(fb).forEach(([k, v]) => doc.text(`  ${k}: ${v}/100`));
    doc.moveDown(0.8);
    doc.fontSize(13).font("Helvetica-Bold").text("REPAIR RECOMMENDATION").moveDown(0.2);
    doc.fontSize(10).font("Helvetica").text(`Category: ${recommendation.repair_category}`).text(`Crew: ${recommendation.estimated_crew}`).text(`Duration: ${recommendation.estimated_duration}`).text(`Cost: Rs.${recommendation.estimated_cost_low_inr} - Rs.${recommendation.estimated_cost_high_inr}`).moveDown(0.3).text(`Explanation: ${recommendation.explanation}`).moveDown(0.8);
    doc.fontSize(13).font("Helvetica-Bold").text("SLA & DISPATCH").moveDown(0.2);
    doc.fontSize(10).font("Helvetica").text(`SLA Deadline: ${new Date(workOrder.sla_deadline).toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })} IST`).text(`Cost Estimate: Rs.${workOrder.cost_estimate}`).text(`Status: ${workOrder.status.toUpperCase()}`).moveDown(1);
    doc.moveTo(50, doc.y).lineTo(550, doc.y).stroke().moveDown(0.5);
    doc.fontSize(8).font("Helvetica-Oblique").text("This work order was auto-generated by the SentriRoad AI system. Cost estimates are prototype values. These are NOT official BBMP/municipal standards.", { align: "center", width: 500 });
    doc.end();
  });
}
module.exports = { generateWorkOrderPdf };
