/**
 * RL ROUTE OPTIMIZER — Q-Learning based route optimization
 * Replaces backend/services/routeOptimizer.js
 */
const RL_CONFIG = { alpha: 0.1, gamma: 0.95, epsilon: 0.1, epsilon_decay: 0.995, min_epsilon: 0.01, urgency_bonus_weight: 2.0, distance_penalty_weight: 1.0, sla_overdue_penalty: 50, episodes_per_route: 100 };
const qTable = new Map();
function getStateKey(currentPos, unvisitedIds) { const latKey = Math.round(currentPos.lat * 1000); const lngKey = Math.round(currentPos.lng * 1000); const unvisitedKey = [...unvisitedIds].sort().join(","); return `${latKey},${lngKey}|${unvisitedKey}`; }
function getQ(stateKey, actionId) { return qTable.get(`${stateKey}:${actionId}`) || 0; }
function setQ(stateKey, actionId, value) { qTable.set(`${stateKey}:${actionId}`, value); }
function computeReward(wo, distance) { let reward = (wo.urgency_score / 100) * RL_CONFIG.urgency_bonus_weight * 10; reward -= distance * RL_CONFIG.distance_penalty_weight; const slaMs = new Date(wo.sla_deadline).getTime() - Date.now(); if (slaMs < 0) reward -= RL_CONFIG.sla_overdue_penalty; else if (slaMs < 6 * 60 * 60 * 1000) reward += 5; return reward; }
function haversine(p1, p2) { const R = 6371; const dLat = (p2.lat - p1.lat) * Math.PI / 180; const dLng = (p2.lng - p1.lng) * Math.PI / 180; const a = Math.sin(dLat / 2) ** 2 + Math.cos(p1.lat * Math.PI / 180) * Math.cos(p2.lat * Math.PI / 180) * Math.sin(dLng / 2) ** 2; return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a)); }
function trainEpisode(workOrders, startPos) { const unvisited = [...workOrders]; let currentPos = startPos, totalReward = 0; const route = []; while (unvisited.length > 0) { const stateKey = getStateKey(currentPos, unvisited.map(w => w.id)); let chosenIdx; if (Math.random() < RL_CONFIG.epsilon) { chosenIdx = Math.floor(Math.random() * unvisited.length); } else { let bestQ = -Infinity; chosenIdx = 0; for (let i = 0; i < unvisited.length; i++) { const q = getQ(stateKey, unvisited[i].id); if (q > bestQ) { bestQ = q; chosenIdx = i; } } } const chosen = unvisited.splice(chosenIdx, 1)[0]; const distance = haversine(currentPos, chosen.location.gps); const reward = computeReward(chosen, distance); const nextStateKey = getStateKey(chosen.location.gps, unvisited.map(w => w.id)); let maxNextQ = 0; if (unvisited.length > 0) { maxNextQ = -Infinity; for (const w of unvisited) { const q = getQ(nextStateKey, w.id); if (q > maxNextQ) maxNextQ = q; } if (maxNextQ === -Infinity) maxNextQ = 0; } const currentQ = getQ(stateKey, chosen.id); setQ(stateKey, chosen.id, currentQ + RL_CONFIG.alpha * (reward + RL_CONFIG.gamma * maxNextQ - currentQ)); totalReward += reward; route.push(chosen); currentPos = chosen.location.gps; } totalReward -= haversine(currentPos, startPos) * RL_CONFIG.distance_penalty_weight; return { route, totalReward }; }
function optimizeRoutes(workOrders, crews, depot = { lat: 12.9716, lng: 77.5946 }) { if (!workOrders.length || !crews.length) return { routes: [], summary: { total_stops: 0, total_distance_km: 0, optimization_method: "Q-Learning (RL)" } }; const sorted = [...workOrders].sort((a, b) => b.urgency_score - a.urgency_score); const assignments = crews.map(c => ({ crew_id: c.id, crew_name: c.name, stops: [] })); sorted.forEach((wo, i) => { assignments[i % crews.length].stops.push(wo); }); const routes = assignments.map(a => { let bestRoute = null, bestReward = -Infinity; for (let ep = 0; ep < RL_CONFIG.episodes_per_route; ep++) { const result = trainEpisode(a.stops, depot); if (result.totalReward > bestReward) { bestReward = result.totalReward; bestRoute = result.route; } RL_CONFIG.epsilon = Math.max(RL_CONFIG.min_epsilon, RL_CONFIG.epsilon * RL_CONFIG.epsilon_decay); } let totalDist = 0, currentPos = depot; for (const wo of bestRoute) { totalDist += haversine(currentPos, wo.location.gps); currentPos = wo.location.gps; } totalDist += haversine(currentPos, depot); return { crew_id: a.crew_id, crew_name: a.crew_name, stops: bestRoute.map((wo, idx) => ({ work_order_id: wo.id, report_id: wo.report_id, address: wo.location.address, gps: wo.location.gps, urgency_score: wo.urgency_score, damage_type: wo.damage_type, stop_number: idx + 1 })), total_distance_km: Math.round(totalDist * 10) / 10, rl_reward: Math.round(bestReward * 100) / 100 }; }); const totalDist = routes.reduce((s, r) => s + r.total_distance_km, 0); return { routes, summary: { total_stops: sorted.length, total_distance_km: Math.round(totalDist * 10) / 10, optimization_method: "Q-Learning (RL)", note: "Trained with " + RL_CONFIG.episodes_per_route + " episodes per crew.", q_table_size: qTable.size, epsilon: RL_CONFIG.epsilon.toFixed(4) } }; }
function exportQTable() { return Object.fromEntries(qTable); }
function importQTable(data) { for (const [k, v] of Object.entries(data)) qTable.set(k, v); console.log(`[RL] Imported ${qTable.size} Q-values`); }
module.exports = { optimizeRoutes, trainEpisode, computeReward, exportQTable, importQTable, RL_CONFIG };
