import { urgencyColor, urgencyText } from '../lib/utils';
export function ScoreBadge({ score }) { return <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold ${urgencyColor(score)}`}>{score} · {urgencyText(score)}</span>; }
export function StatusBadge({ status }) { const m = { reported: 'bg-blue-100 text-blue-700', scored: 'bg-purple-100 text-purple-700', dispatched: 'bg-indigo-100 text-indigo-700', assigned_to_crew: 'bg-amber-100 text-amber-700', crew_submitted: 'bg-cyan-100 text-cyan-700', reviewing: 'bg-violet-100 text-violet-700', repaired: 'bg-teal-100 text-teal-700', verified: 'bg-green-100 text-green-700', rejected_by_crew_review: 'bg-red-100 text-red-700' }; return <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${m[status] || 'bg-slate-100 text-slate-700'}`}>{status.replace(/_/g, ' ')}</span>; }
export function Card({ children, className = '' }) { return <div className={`bg-white rounded-xl shadow-sm border border-sentri-border p-6 ${className}`}>{children}</div>; }
export function MetricCard({ label, value, icon: Icon, color = 'text-sentri-primary' }) { return <Card className="flex items-center gap-4">{Icon && <div className={`w-12 h-12 rounded-lg bg-slate-50 flex items-center justify-center ${color}`}><Icon size={24} /></div>}<div><div className="text-2xl font-bold text-slate-800">{value}</div><div className="text-sm text-slate-500">{label}</div></div></Card>; }
export function Button({ children, variant = 'primary', className = '', ...props }) { const v = { primary: 'bg-sentri-primary text-white hover:bg-sentri-dark', danger: 'bg-red-500 text-white hover:bg-red-600', success: 'bg-green-500 text-white hover:bg-green-600', outline: 'border border-slate-300 text-slate-700 hover:bg-slate-50', ghost: 'text-slate-600 hover:bg-slate-100' }; return <button className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors disabled:opacity-50 ${v[variant]} ${className}`} {...props}>{children}</button>; }
export function ScoreBreakdown({ score }) { if (!score?.factor_breakdown) return null; const fb = score.factor_breakdown; const factors = [{ label: 'Severity', value: fb.severity, weight: '40%' }, { label: 'Traffic Volume', value: fb.traffic, weight: '20%' }, { label: 'Rainfall', value: fb.rainfall, weight: '10%' }, { label: 'Road Importance', value: fb.road_importance, weight: '10%' }, { label: 'Sensitive Location', value: fb.sensitive_location, weight: '10%' }, { label: 'Citizen Complaints', value: fb.citizen_complaints, weight: '10%' }]; return (<div className="space-y-3"><div className="flex items-center justify-between mb-2"><span className="text-sm font-medium text-slate-600">Priority Score Breakdown</span><span className="text-lg font-bold text-sentri-dark">{score.urgency_score}/100</span></div>{factors.map((f) => (<div key={f.label}><div className="flex items-center justify-between text-xs mb-1"><span className="text-slate-600">{f.label} <span className="text-slate-400">({f.weight})</span></span><span className="font-medium text-slate-700">{f.value}/100</span></div><div className="h-2 bg-slate-100 rounded-full overflow-hidden"><div className={`h-full rounded-full ${urgencyColor(f.value).split(' ')[0]}`} style={{ width: `${f.value}%` }} /></div></div>))}</div>); }
export function EmptyState({ icon: Icon, title, subtitle }) { return <div className="flex flex-col items-center justify-center py-12 text-center">{Icon && <Icon size={48} className="text-slate-300 mb-4" />}<h3 className="text-lg font-medium text-slate-600">{title}</h3>{subtitle && <p className="text-sm text-slate-400 mt-1">{subtitle}</p>}</div>; }
export function LoadingSpinner({ label = 'Loading...' }) { return <div className="flex items-center justify-center py-12"><div className="w-8 h-8 border-3 border-sentri-primary border-t-transparent rounded-full animate-spin"></div><span className="ml-3 text-slate-500">{label}</span></div>; }
