import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import api from '../lib/api';
import { Card, Button, StatusBadge, EmptyState, LoadingSpinner } from '../components/UI';
import { citizenStatus, formatTimeAgo } from '../lib/utils';
import { Plus, FileText, MapPin, Upload } from 'lucide-react';

export default function CitizenDashboard() {
  const [reports, setReports] = useState([]); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false);
  useEffect(() => { load(); }, []);
  async function load() { try { const res = await api.get('/reports'); setReports(res.data.data); } catch (e) { console.error(e); } setLoading(false); }
  if (loading) return <LoadingSpinner />;
  return (<div className="p-8 max-w-6xl mx-auto"><div className="flex items-center justify-between mb-8"><div><h1 className="text-2xl font-bold text-slate-800">My Reports</h1><p className="text-sm text-slate-500 mt-1">Track your road damage reports</p></div><Button onClick={() => setShowForm(!showForm)}><Plus size={16} className="inline mr-1" />Report Pothole</Button></div>{showForm && <ReportForm onSubmitted={() => { setShowForm(false); load(); }} />}{reports.length === 0 ? <EmptyState icon={FileText} title="No reports yet" subtitle="Click Report Pothole to submit" /> : <div className="grid gap-4">{reports.map((r) => <Link key={r.id} to={`/reports/${r.id}`} className="block bg-white rounded-xl shadow-sm border border-sentri-border p-5 hover:shadow-md"><div className="flex items-start justify-between"><div className="flex-1"><div className="flex items-center gap-2 mb-2"><span className="text-sm font-mono text-slate-400">{r.id}</span><StatusBadge status={r.status} /></div><h3 className="font-medium text-slate-800">{r.address || `${r.gps.lat}, ${r.gps.lng}`}</h3><p className="text-sm text-slate-500 mt-1">{r.description || 'No description'}</p><div className="flex items-center gap-4 mt-3 text-xs text-slate-400"><span className="flex items-center gap-1"><MapPin size={12} />{r.gps.lat.toFixed(4)}, {r.gps.lng.toFixed(4)}</span><span>{formatTimeAgo(r.created_at)}</span><span className="font-medium text-slate-600">{citizenStatus(r.status)}</span></div></div>{r.media_url && <img src={r.media_url} alt="" className="w-24 h-24 rounded-lg object-cover ml-4" />}</div></Link>)}</div>}</div>);
}

function ReportForm({ onSubmitted }) {
  const [gps, setGps] = useState(null); const [description, setDescription] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { if (navigator.geolocation) navigator.geolocation.getCurrentPosition((p) => setGps({ lat: p.coords.latitude, lng: p.coords.longitude }), () => setGps({ lat: 12.9716, lng: 77.5946 })); else setGps({ lat: 12.9716, lng: 77.5946 }); }, []);
  async function handleSubmit(e) { e.preventDefault(); setLoading(true); try { const signed = await api.post('/uploads/signed-url', { filename: 'pothole.jpg', content_type: 'image/jpeg' }); await api.post('/reports', { media_url: signed.data.public_url_after_upload, media_type: 'photo', gps: gps || { lat: 12.9716, lng: 77.5946 }, address: gps ? `${gps.lat.toFixed(4)}, ${gps.lng.toFixed(4)}` : 'Bengaluru', description }); onSubmitted(); } catch (e) { console.error(e); } setLoading(false); }
  return (<Card className="mb-6"><h3 className="font-semibold text-slate-800 mb-4">Report a Pothole</h3><form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-2 gap-4"><div><label className="block text-sm font-medium text-slate-600 mb-1">Photo</label><div className="border-2 border-dashed border-slate-300 rounded-lg p-4 text-center"><Upload size={24} className="mx-auto text-slate-400 mb-2" /><p className="text-xs text-slate-400">Photo auto-attached (demo)</p></div></div><div><label className="block text-sm font-medium text-slate-600 mb-1">GPS Location</label><div className="px-3 py-2.5 bg-slate-50 rounded-lg text-sm text-slate-600">{gps ? `${gps.lat.toFixed(6)}, ${gps.lng.toFixed(6)}` : 'Detecting...'}</div></div></div><div><label className="block text-sm font-medium text-slate-600 mb-1">Description (optional)</label><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={2} className="w-full px-3 py-2 rounded-lg border border-slate-300 outline-none focus:ring-2 focus:ring-sentri-primary" placeholder="e.g. Big pothole near the bus stop" /></div><Button type="submit" disabled={loading}>{loading ? 'Submitting...' : 'Submit Report'}</Button></form></Card>);
}
