import { useState } from 'react';
import api from '../lib/api';
import { Card, Button, ScoreBadge, ScoreBreakdown } from '../components/UI';
import { formatINR } from '../lib/utils';
import { Zap, CheckCircle } from 'lucide-react';
const STEPS = [{key:'login',label:'Authenticate',icon:CheckCircle},{key:'upload',label:'Load Demo Image',icon:CheckCircle},{key:'detect',label:'Run AI Detection',icon:Zap},{key:'score',label:'Calculate Priority Score',icon:Zap},{key:'recommend',label:'Generate Recommendation',icon:Zap},{key:'workorder',label:'Create Work Order',icon:Zap},{key:'escalate',label:'Critical Alert',icon:Zap},{key:'done',label:'Dashboard Updated',icon:CheckCircle}];
export default function DemoMode() {
  const [running, setRunning] = useState(false); const [step, setStep] = useState(-1); const [results, setResults] = useState({}); const [error, setError] = useState('');
  async function runDemo() {
    setRunning(true); setError(''); setResults({}); setStep(0);
    try {
      const loginRes = await api.post('/auth/login', { email: 'suresh.authority@bbmp.gov.in', password: 'demo' }); localStorage.setItem('sentriroad_token', loginRes.data.token); localStorage.setItem('sentriroad_user', JSON.stringify(loginRes.data.user)); setStep(1); await sleep(500);
      const citizenLogin = await api.post('/auth/login', { email: 'ravi@example.com', password: 'demo' }); const reportRes = await api.post('/reports', { media_url: 'https://picsum.photos/seed/demo/800/600', media_type: 'photo', gps: { lat: 12.9716, lng: 77.5946 }, address: 'Outer Ring Road, Bengaluru', description: 'Demo pothole' }, { headers: { Authorization: `Bearer ${citizenLogin.data.token}` } }); setResults(r => ({...r, report: reportRes.data})); setStep(2); await sleep(500);
      const analysisRes = await api.post(`/reports/${reportRes.data.id}/analyze`, null, { headers: { Authorization: `Bearer ${loginRes.data.token}` } }); setResults(r => ({...r, analysis: analysisRes.data})); setStep(3); await sleep(500); setStep(4); await sleep(500); setStep(5); await sleep(500);
      if (analysisRes.data.score?.urgency_score >= 80) { setStep(6); await sleep(500); }
      setResults(r => ({...r, complete: true})); setStep(7);
    } catch (err) { setError(err.response?.data?.error?.message || err.message); } setRunning(false);
  }
  return (<div className="p-8 max-w-4xl mx-auto"><div className="text-center mb-8"><div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-sentri-accent mb-4"><Zap size={32} className="text-sentri-dark" /></div><h1 className="text-2xl font-bold">Demo Mode</h1><p className="text-sm text-slate-500 mt-2">One-click closed-loop walkthrough</p></div><div className="text-center mb-8"><Button onClick={runDemo} disabled={running} className="text-lg px-8 py-3">{running ? 'Running...' : 'Run Demo Inspection'}</Button>{error && <p className="mt-3 text-sm text-red-600">{error}</p>}</div><div className="space-y-3 mb-6">{STEPS.map((s, i) => { const done = step > i; const active = step === i; const Icon = s.icon; return <div key={s.key} className={`flex items-center gap-4 p-4 rounded-xl border ${done ? 'bg-green-50 border-green-200' : active ? 'bg-sentri-primary/10 border-sentri-primary' : 'bg-white border-slate-200'}`}><div className={`w-10 h-10 rounded-full flex items-center justify-center ${done ? 'bg-green-500 text-white' : active ? 'bg-sentri-primary text-white animate-pulse' : 'bg-slate-100 text-slate-400'}`}>{done ? <CheckCircle size={20} /> : <Icon size={18} />}</div><span className={`text-sm font-medium ${done || active ? 'text-slate-800' : 'text-slate-400'}`}>{s.label}</span></div>; })}</div>{results.report && <Card><h3 className="font-semibold mb-4">Results</h3><div className="grid grid-cols-2 gap-4 text-sm"><div><div className="text-xs text-slate-400">Report ID</div><div className="font-mono">{results.report.id}</div></div>{results.analysis?.score && <div><div className="text-xs text-slate-400">Score</div><ScoreBadge score={results.analysis.score.urgency_score} /></div>}{results.analysis?.work_order && <div><div className="text-xs text-slate-400">Work Order</div><div className="font-mono">{results.analysis.work_order.id}</div></div>}{results.analysis?.work_order?.recommendation && <div className="col-span-2"><div className="text-xs text-slate-400">Recommendation</div><div className="font-medium">{results.analysis.work_order.recommendation.repair_category}</div></div>}</div>{results.complete && <div className="mt-4 p-3 bg-green-50 border border-green-200 rounded-lg text-sm text-green-700 flex items-center gap-2"><CheckCircle size={16} />Demo complete!</div>}</Card>}</div>);
}
function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
