import { useState, useEffect } from 'react';
import api from '../lib/api';
import { Card, Button, LoadingSpinner } from '../components/UI';
import { MapContainer, TileLayer, CircleMarker, Popup } from 'react-leaflet';
import { Drone, Upload, Battery } from 'lucide-react';
const BLR = [12.9716, 77.5946];
export default function DroneDashboard() {
  const [zones, setZones] = useState([]); const [loading, setLoading] = useState(true); const [uploadMsg, setUploadMsg] = useState('');
  useEffect(() => { load(); }, []);
  async function load() { try { const res = await api.get('/zones/priority'); setZones(res.data.data); } catch (e) { console.error(e); } setLoading(false); }
  async function handleUpload() { try { const signed = await api.post('/uploads/signed-url', { filename: 'drone.mp4', content_type: 'video/mp4' }); const res = await api.post('/drone/footage', { media_url: signed.data.public_url_after_upload, zone_id: zones[0]?.id }); setUploadMsg(`Uploaded — Job: ${res.data.job_id}`); } catch (e) { console.error(e); } }
  if (loading) return <LoadingSpinner />;
  return (<div className="p-8 max-w-7xl mx-auto"><div className="flex items-center justify-between mb-6"><div><h1 className="text-2xl font-bold text-slate-800 flex items-center gap-2"><Drone size={24} /> Drone Operations</h1><p className="text-sm text-slate-500 mt-1">Priority zones and footage upload</p></div><Button onClick={handleUpload}><Upload size={16} className="inline mr-1" />Upload Footage</Button></div>{uploadMsg && <div className="mb-4 p-3 bg-green-50 border border-green-200 rounded-lg text-sm text-green-700">{uploadMsg}</div>}<div className="grid grid-cols-3 gap-6"><div className="col-span-2"><Card className="p-0 overflow-hidden"><div className="p-4 border-b"><h3 className="font-semibold text-slate-800">Priority Zone Map</h3></div><div className="h-[500px]"><MapContainer center={BLR} zoom={12} style={{height:'100%',width:'100%'}}><TileLayer url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" />{zones.map(z => { const c = z.priority === 'critical' ? 'red' : z.priority === 'high' ? 'orange' : z.priority === 'medium' ? 'yellow' : 'green'; return <CircleMarker key={z.id} center={[z.gps.lat, z.gps.lng]} radius={z.work_order_count * 5 + 8} pathOptions={{color: c, fillColor: c, fillOpacity: 0.4}}><Popup><strong>{z.name}</strong><br />Priority: {z.priority}<br />WOs: {z.work_order_count}<br />Battery saving: {z.estimated_battery_saving_pct}%</Popup></CircleMarker>; })}</MapContainer></div></Card></div><div><Card><h3 className="font-semibold text-slate-800 mb-3">Zones</h3><div className="space-y-3">{zones.map(z => <div key={z.id} className="p-3 bg-slate-50 rounded-lg"><div className="flex items-center justify-between mb-1"><span className="text-sm font-medium">{z.name}</span><span className={`text-xs px-2 py-0.5 rounded-full ${z.priority === 'critical' ? 'bg-red-100 text-red-700' : z.priority === 'high' ? 'bg-orange-100 text-orange-700' : 'bg-yellow-100 text-yellow-700'}`}>{z.priority}</span></div><div className="flex items-center gap-3 text-xs text-slate-500"><span>{z.work_order_count} WOs</span><span className="flex items-center gap-1"><Battery size={12} />{z.estimated_battery_saving_pct}%</span></div></div>)}</div></Card></div></div></div>);
}
