import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../hooks/useAuth';
import { DEMO_ACCOUNTS } from '../lib/utils';
import { Shield, AlertCircle } from 'lucide-react';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function handleSubmit(e) { e.preventDefault(); setError(''); setLoading(true); try { const user = await login(email, password); if (user.role === 'citizen') navigate('/citizen'); else if (user.role === 'authority' || user.role === 'admin') navigate('/authority'); else if (user.role === 'crew') navigate('/crew'); } catch (err) { setError(err.response?.data?.error?.message || 'Login failed'); } setLoading(false); }
  function quickLogin(em) { setEmail(em); setPassword('demo'); }
  return (<div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-sentri-dark via-sentri-primary to-sentri-dark p-4"><div className="w-full max-w-md"><div className="text-center mb-8"><div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-sentri-accent mb-4"><Shield size={32} className="text-sentri-dark" /></div><h1 className="text-2xl font-bold text-white">SentriRoad</h1><p className="text-white/60 text-sm mt-1">AI Road Inspector</p></div><div className="bg-white rounded-2xl shadow-xl p-8"><h2 className="text-lg font-semibold text-slate-800 mb-4">Sign In</h2>{error && <div className="mb-4 p-3 bg-red-50 border border-red-200 rounded-lg flex items-center gap-2 text-sm text-red-700"><AlertCircle size={16} />{error}</div>}<form onSubmit={handleSubmit} className="space-y-4"><div><label className="block text-sm font-medium text-slate-600 mb-1">Email</label><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 focus:ring-2 focus:ring-sentri-primary outline-none" placeholder="you@example.com" required /></div><div><label className="block text-sm font-medium text-slate-600 mb-1">Password</label><input type="password" value={password} onChange={(e) => setPassword(e.target.value)} className="w-full px-4 py-2.5 rounded-lg border border-slate-300 focus:ring-2 focus:ring-sentri-primary outline-none" placeholder="demo" required /></div><button type="submit" disabled={loading} className="w-full bg-sentri-primary text-white py-2.5 rounded-lg font-medium hover:bg-sentri-dark disabled:opacity-50">{loading ? 'Signing in...' : 'Sign In'}</button></form><div className="mt-6 pt-6 border-t border-slate-100"><p className="text-xs font-medium text-slate-500 mb-3">Quick demo login (password: demo):</p><div className="space-y-1.5">{DEMO_ACCOUNTS.map((a) => <button key={a.email} onClick={() => quickLogin(a.email)} className="w-full text-left px-3 py-2 rounded-lg hover:bg-slate-50 flex items-center justify-between text-sm"><span className="text-slate-700">{a.label}</span><span className="text-xs text-slate-400 capitalize">{a.role}</span></button>)}</div></div></div></div></div>);
}
