/**
 * MONGOOSE SCHEMAS — MongoDB-ready models
 * To switch from in-memory to MongoDB:
 * 1. npm install mongoose
 * 2. Add DB_URL=mongodb://localhost:27017/sentriroad to .env
 * 3. Replace backend/models/db.js with mongoose.connect()
 * 4. Import these schemas in each model file
 */
const mongoose = require("mongoose");
const UserSchema = new mongoose.Schema({ name: { type: String, required: true }, email: { type: String, required: true, unique: true, index: true }, phone: { type: String, default: null }, role: { type: String, enum: ["citizen", "authority", "crew", "admin"], required: true }, password_hash: { type: String, default: null }, created_at: { type: Date, default: Date.now } }, { collection: "users" });
const ReportSchema = new mongoose.Schema({ citizen_id: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true, index: true }, media_url: { type: String, required: true }, media_type: { type: String, enum: ["photo", "video"], required: true }, gps: { lat: { type: Number, required: true }, lng: { type: Number, required: true } }, address: { type: String, default: null }, description: { type: String, default: null }, status: { type: String, enum: ["reported", "scored", "dispatched", "assigned_to_crew", "crew_submitted", "reviewing", "verified"], default: "reported", index: true }, created_at: { type: Date, default: Date.now } }, { collection: "reports" });
ReportSchema.index({ "gps": "2dsphere" });
const DetectionSchema = new mongoose.Schema({ report_id: { type: mongoose.Schema.Types.ObjectId, ref: "Report", required: true, index: true }, damage_type: { type: String, enum: ["pothole", "crack"], required: true }, confidence: { type: Number, required: true, min: 0, max: 1 }, bounding_box: [{ type: Number }], evidence_image_url: { type: String, required: true }, frame_timestamp_seconds: { type: Number, default: null }, source_type: { type: String, enum: ["MODEL", "DEMO"], default: "DEMO" }, created_at: { type: Date, default: Date.now } }, { collection: "detections" });
const ScoreSchema = new mongoose.Schema({ detection_id: { type: mongoose.Schema.Types.ObjectId, ref: "Detection", required: true, index: true }, urgency_score: { type: Number, required: true, min: 0, max: 100 }, factor_breakdown: { severity: { type: Number, default: 0 }, traffic: { type: Number, default: 0 }, rainfall: { type: Number, default: 0 }, road_importance: { type: Number, default: 0 }, sensitive_location: { type: Number, default: 0 }, citizen_complaints: { type: Number, default: 0 } }, computed_at: { type: Date, default: Date.now } }, { collection: "scores" });
const WorkOrderSchema = new mongoose.Schema({ report_id: { type: mongoose.Schema.Types.ObjectId, ref: "Report", required: true, index: true }, score_id: { type: mongoose.Schema.Types.ObjectId, ref: "Score", required: true }, location: { address: { type: String, default: "" }, gps: { lat: { type: Number, required: true }, lng: { type: Number, required: true } } }, evidence_image_url: { type: String, required: true }, damage_type: { type: String, enum: ["pothole", "crack"], required: true }, urgency_score: { type: Number, required: true, min: 0, max: 100 }, cost_estimate: { type: Number, default: 0 }, sla_deadline: { type: Date, required: true }, status: { type: String, enum: ["scored", "dispatched", "assigned_to_crew", "crew_submitted", "reviewing", "verified"], default: "scored", index: true }, assigned_crew_id: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null }, crew_submitted_at: { type: Date, default: null }, crew_photo_url: { type: String, default: null }, crew_notes: { type: String, default: null }, review_status: { type: String, enum: ["pending", "approved", "rejected"], default: null }, reviewed_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", default: null }, reviewed_at: { type: Date, default: null }, rejection_reason: { type: String, default: null }, pdf_url: { type: String, default: null }, recommendation: { size_category: String, repair_category: String, suggested_kit: [String], estimated_crew: String, estimated_duration: String, estimated_cost_low_inr: Number, estimated_cost_high_inr: Number, explanation: String, disclaimer: String }, created_at: { type: Date, default: Date.now }, updated_at: { type: Date, default: Date.now } }, { collection: "workorders" });
const VerificationSchema = new mongoose.Schema({ work_order_id: { type: mongoose.Schema.Types.ObjectId, ref: "WorkOrder", required: true, index: true }, before_image: { type: String, required: true }, after_image: { type: String, required: true }, verified_by: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true }, verified_at: { type: Date, default: Date.now } }, { collection: "verifications" });
const FeedbackSchema = new mongoose.Schema({ report_id: { type: mongoose.Schema.Types.ObjectId, ref: "Report", required: true, index: true }, citizen_id: { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true }, rating: { type: Number, required: true, min: 1, max: 5 }, comment: { type: String, default: null }, created_at: { type: Date, default: Date.now } }, { collection: "feedback" });
const AlertSchema = new mongoose.Schema({ work_order_id: { type: mongoose.Schema.Types.ObjectId, ref: "WorkOrder", required: true }, report_id: { type: mongoose.Schema.Types.ObjectId, ref: "Report", required: true }, priority_score: { type: Number, required: true }, priority_level: { type: String, enum: ["CRITICAL", "HIGH", "MEDIUM", "LOW"] }, location: { address: String, gps: { lat: Number, lng: Number } }, damage_type: String, message: String, status: { type: String, enum: ["active", "acknowledged", "resolved"], default: "active" }, created_at: { type: Date, default: Date.now } }, { collection: "alerts" });
const DroneFootageSchema = new mongoose.Schema({ media_url: { type: String, required: true }, zone_id: { type: String, default: null }, job_id: { type: String, required: true }, status: { type: String, enum: ["processing", "completed", "failed"], default: "processing" }, extracted_reports: [{ type: mongoose.Schema.Types.ObjectId, ref: "Report" }], created_at: { type: Date, default: Date.now } }, { collection: "drone_footage" });
function createModels(connection) { return { User: connection.model("User", UserSchema), Report: connection.model("Report", ReportSchema), Detection: connection.model("Detection", DetectionSchema), Score: connection.model("Score", ScoreSchema), WorkOrder: connection.model("WorkOrder", WorkOrderSchema), Verification: connection.model("Verification", VerificationSchema), Feedback: connection.model("Feedback", FeedbackSchema), Alert: connection.model("Alert", AlertSchema), DroneFootage: connection.model("DroneFootage", DroneFootageSchema) }; }
module.exports = { UserSchema, ReportSchema, DetectionSchema, ScoreSchema, WorkOrderSchema, VerificationSchema, FeedbackSchema, AlertSchema, DroneFootageSchema, createModels };
